'use client'

import React from 'react'
import { Bot, FileText, ShieldAlert } from 'lucide-react'
import type { Investigation } from '@/lib/types'

export function InvestigationPanel({ investigation }: { investigation: Investigation }) {
  const isLLM = investigation._source === 'llm'

  return (
    <div className="bg-surface rounded-xl shadow-card overflow-hidden">
      <div className="flex items-center justify-between px-5 py-3.5 bg-brand-50 border-b border-line">
        <div className="flex items-center gap-2">
          <Bot className="w-4 h-4 text-brand-600" />
          <h3 className="text-sm font-display font-semibold text-ink">AI Investigation</h3>
        </div>
        {isLLM ? (
          <span className="text-xs font-medium px-2.5 py-1 rounded-full bg-brand-600 text-white">
            Generated by Gemini
          </span>
        ) : (
          <span
            className="text-xs font-medium px-2.5 py-1 rounded-full bg-white text-slate-500 border border-line flex items-center gap-1"
            title={investigation._fallback_reason ?? 'LLM unavailable'}
          >
            <FileText className="w-3 h-3" /> Deterministic fallback (LLM unavailable)
          </span>
        )}
      </div>

      <div className="p-5">
        <p className="text-sm text-ink mb-4">{investigation.incident_summary}</p>

        <div className="mb-4">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Primary Hypothesis</p>
          <p className="text-sm text-ink">{investigation.primary_hypothesis}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <div>
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Supporting Evidence</p>
            <ul className="text-sm text-slate-700 space-y-1 list-disc list-inside">
              {investigation.supporting_evidence.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </div>
          <div>
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Contradicting Evidence</p>
            {investigation.contradicting_evidence.length > 0 ? (
              <ul className="text-sm text-slate-700 space-y-1 list-disc list-inside">
                {investigation.contradicting_evidence.map((item, i) => (
                  <li key={i}>{item}</li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-slate-400 italic">None identified</p>
            )}
          </div>
        </div>

        {investigation.unknowns.length > 0 && (
          <div className="mb-4 bg-amber-50 border border-amber-200 rounded-lg p-3">
            <div className="flex items-center gap-1.5 mb-1">
              <ShieldAlert className="w-3.5 h-3.5 text-amber-600" />
              <p className="text-xs font-semibold text-amber-800 uppercase tracking-wide">Unknowns</p>
            </div>
            <ul className="text-sm text-amber-900 space-y-1 list-disc list-inside">
              {investigation.unknowns.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-3 border-t border-line">
          <div>
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Recommended Next Step</p>
            <p className="text-sm text-ink">{investigation.recommended_next_step}</p>
          </div>
          <div>
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Confidence</p>
            <p className="text-sm text-ink">{investigation.confidence_commentary}</p>
          </div>
        </div>
      </div>
    </div>
  )
}
