'use client'

import React from 'react'
import { Bot, FileText, ShieldAlert } from 'lucide-react'
import type { Investigation } from '@/lib/types'

export function InvestigationPanel({ investigation }: { investigation: Investigation }) {
  const isLLM = investigation._source === 'llm'

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-5">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Bot className="w-4 h-4 text-violet-600" />
          <h3 className="text-sm font-semibold text-gray-900">AI Investigation</h3>
        </div>
        {isLLM ? (
          <span className="text-xs font-medium px-2 py-1 rounded bg-violet-100 text-violet-700">
            Generated by Gemini
          </span>
        ) : (
          <span
            className="text-xs font-medium px-2 py-1 rounded bg-gray-100 text-gray-600 flex items-center gap-1"
            title={investigation._fallback_reason ?? 'LLM unavailable'}
          >
            <FileText className="w-3 h-3" /> Deterministic fallback (LLM unavailable)
          </span>
        )}
      </div>

      <p className="text-sm text-gray-800 mb-4">{investigation.incident_summary}</p>

      <div className="mb-4">
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Primary Hypothesis</p>
        <p className="text-sm text-gray-800">{investigation.primary_hypothesis}</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Supporting Evidence</p>
          <ul className="text-sm text-gray-700 space-y-1 list-disc list-inside">
            {investigation.supporting_evidence.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </div>
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Contradicting Evidence</p>
          {investigation.contradicting_evidence.length > 0 ? (
            <ul className="text-sm text-gray-700 space-y-1 list-disc list-inside">
              {investigation.contradicting_evidence.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-gray-400 italic">None identified</p>
          )}
        </div>
      </div>

      {investigation.unknowns.length > 0 && (
        <div className="mb-4 bg-amber-50 border border-amber-200 rounded-md p-3">
          <div className="flex items-center gap-1.5 mb-1">
            <ShieldAlert className="w-3.5 h-3.5 text-amber-600" />
            <p className="text-xs font-semibold text-amber-800 uppercase tracking-wide">Unknowns</p>
          </div>
          <ul className="text-sm text-amber-900 space-y-1 list-disc list-inside">
            {investigation.unknowns.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-3 border-t border-gray-100">
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Recommended Next Step</p>
          <p className="text-sm text-gray-800">{investigation.recommended_next_step}</p>
        </div>
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Confidence</p>
          <p className="text-sm text-gray-800">{investigation.confidence_commentary}</p>
        </div>
      </div>
    </div>
  )
}
