'use client'

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { AlertTriangle, ArrowLeft, Bot, CheckCircle2, FileText, XCircle } from 'lucide-react'
import { DashboardLayout } from '@/components/DashboardLayout'
import { StatTile } from '@/components/StatTile'
import { Badge } from '@/components/Badge'
import { chargebackApi } from '@/lib/api'
import { formatDateTime, formatINR, reasonCodeLabel, recommendationStyle } from '@/lib/format'
import type { ChargebackCaseDetail } from '@/lib/types'

export default function ChargebackCasePage() {
  const params = useParams<{ id: string }>()
  const [c, setCase] = useState<ChargebackCaseDetail | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    chargebackApi
      .getCase(params.id)
      .then((res) => setCase(res.data))
      .catch(() => setError('Case not found, or the API is unreachable.'))
  }, [params.id])

  if (error) {
    return (
      <DashboardLayout>
        <p className="text-sm text-risk-600">{error}</p>
      </DashboardLayout>
    )
  }
  if (!c) {
    return (
      <DashboardLayout>
        <p className="text-sm text-slate-500">Loading...</p>
      </DashboardLayout>
    )
  }

  const style = recommendationStyle(c.recommendation)
  const isLLM = c.draft._source === 'llm'

  return (
    <DashboardLayout>
      <Link href="/chargebacks" className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-ink mb-4">
        <ArrowLeft className="w-4 h-4" /> Back to Chargebacks
      </Link>

      <div className="flex items-start justify-between mb-6">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <h1 className="text-2xl font-display font-semibold text-ink tracking-tight">{reasonCodeLabel(c.reason_code)}</h1>
            <Badge tone={style} label={`Recommendation: ${style.label}`} />
          </div>
          <p className="text-sm text-slate-500 font-mono">
            {c.case_id} &middot; {c.merchant_name} &middot; transaction {c.transaction_id}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-5 mb-8">
        <StatTile
          label="Amount"
          value={formatINR(c.amount)}
          sublabel={`Disputed ${formatDateTime(c.disputed_at)}`}
          icon={AlertTriangle}
          iconColor="text-risk-500"
        />
        <StatTile
          label="Evidence Completeness"
          value={`${(c.evidence_completeness * 100).toFixed(0)}%`}
          sublabel={`for a ${reasonCodeLabel(c.reason_code)} dispute`}
          icon={FileText}
          iconColor="text-brand-600"
        />
        <StatTile
          label="Customer History"
          value={String(c.customer_context.prior_successful_deliveries)}
          sublabel="prior successful deliveries"
          icon={CheckCircle2}
          iconColor="text-success"
        />
        <StatTile
          label="Order Placed"
          value={formatDateTime(c.order_timestamp)}
          sublabel={c.customer_context.is_established ? 'Established customer' : 'New customer (no prior history)'}
          icon={FileText}
          iconColor="text-slate-500"
        />
      </div>

      {c.linked_loss_event && (
        <div className="mb-8 bg-violet-50 border border-violet-200 rounded-xl p-4">
          <p className="text-sm text-violet-900">
            This dispute is connected to{' '}
            <Link href={`/incidents/${c.linked_loss_event.event_id}`} className="font-semibold underline">
              Loss Event {c.linked_loss_event.event_id}
            </Link>{' '}
            ({c.linked_loss_event.event_type.replace(/_/g, ' ')}), independently flagged at{' '}
            {(c.linked_loss_event.confidence * 100).toFixed(0)}% confidence before this dispute arrived.
          </p>
        </div>
      )}

      <div className="bg-surface rounded-xl shadow-card overflow-hidden mb-8">
        <div className="flex items-center justify-between px-5 py-3.5 bg-brand-50 border-b border-line">
          <div className="flex items-center gap-2">
            <Bot className="w-4 h-4 text-brand-600" />
            <h3 className="text-sm font-display font-semibold text-ink">Response Draft</h3>
          </div>
          {isLLM ? (
            <span className="text-xs font-medium px-2.5 py-1 rounded-full bg-brand-600 text-white">Generated by Gemini</span>
          ) : (
            <span
              className="text-xs font-medium px-2.5 py-1 rounded-full bg-white text-slate-500 border border-line"
              title={c.draft._fallback_reason ?? 'LLM unavailable'}
            >
              Deterministic fallback (LLM unavailable)
            </span>
          )}
        </div>
        <div className="p-5">
          <p className="text-sm text-ink mb-3">{c.draft.case_summary}</p>
          <div className="bg-canvas rounded-lg p-3 text-sm text-ink mb-3 whitespace-pre-wrap">
            {c.draft.response_text}
          </div>
          {c.draft.caveats.length > 0 && (
            <ul className="text-xs text-amber-700 list-disc list-inside space-y-0.5">
              {c.draft.caveats.map((cv, i) => (
                <li key={i}>{cv}</li>
              ))}
            </ul>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <section>
          <h2 className="text-lg font-display font-semibold text-ink mb-3">Evidence Checklist</h2>
          <p className="text-xs text-slate-500 mb-3">{c.recommendation_reasoning}</p>
          <div className="space-y-2">
            {c.evidence.map((e, i) => (
              <div key={i} className="flex items-start gap-2 bg-surface shadow-card rounded-lg px-4 py-3">
                {e.status === 'present' ? (
                  <CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" />
                ) : (
                  <XCircle className="w-4 h-4 text-slate-300 shrink-0 mt-0.5" />
                )}
                <div>
                  <p className="text-sm font-medium text-ink capitalize">{e.type.replace(/_/g, ' ')}</p>
                  <p className="text-xs text-slate-500">{e.detail}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-lg font-display font-semibold text-ink mb-3">Contradictions</h2>
          {c.contradictions.length > 0 ? (
            <div className="space-y-2">
              {c.contradictions.map((cd, i) => (
                <div key={i} className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-3">
                  <p className="text-xs font-semibold text-amber-800 uppercase tracking-wide mb-1">
                    {cd.type.replace(/_/g, ' ')}
                  </p>
                  <p className="text-sm text-amber-900">{cd.description}</p>
                </div>
              ))}
            </div>
          ) : (
            <div className="h-full bg-surface rounded-xl border border-dashed border-line flex items-center justify-center p-8">
              <p className="text-sm text-slate-500 text-center">
                No contradictions detected in the merchant&apos;s own records for this dispute.
              </p>
            </div>
          )}
        </section>
      </div>
    </DashboardLayout>
  )
}
